# Generated by Django 4.1.7 on 2023-04-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdevelopmentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=250)),
                ('person_image', models.ImageField(upload_to='myteampicture')),
                ('designation', models.TextField()),
            ],
        ),
    ]
